# -*- coding: utf-8 -*-
"""Diff. GD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eluBZaIspA0DtMoYIvFtgA1ucxG5Rq-5
"""

import numpy as np
import pandas as pd

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

import zipfile
zip = zipfile.ZipFile('/content/archive(7).zip')
zip.extractall()
zip.close()

df = pd.read_csv('/content/Social_Network_Ads.csv')
df.head()

if 'User ID' in df.columns:
  df.drop(['User ID'], axis=1, inplace=True)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

df

X = df.drop(['Purchased'], axis=1)
y = df['Purchased']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled.shape

model = Sequential()
model.add(Dense(32, activation='relu', input_dim = 3))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy',metrics=['Accuracy'])

model.summary()

"""## Batch GD"""

import time
start_time = time.time()
model.fit(X_scaled, y, batch_size=1, epochs=30, verbose=1, validation_split=0.2)
print(time.time()-start_time)

"""## Stochastic GD"""

model.compile(optimizer=Adam(learning_rate=0.01), loss='binary_crossentropy',metrics=['Accuracy'])
start_time = time.time()
model.fit(X_scaled, y, batch_size=320, epochs=30, validation_split=0.2)
print(time.time()-start_time)

"""## Mini-Batch GD"""

start_time = time.time()
model.fit(X_scaled, y, batch_size = 20,epochs=30,validation_split=0.2)
print(time.time()-start_time)